# Generated by Django 5.1.5 on 2025-01-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_interaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
